server:
  port : 8086

spring:
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:todolist
      username: Alisa
      password: 123
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true